---
kind: job
apiVersion: batch/v1
metadata:
  name: prepare-features
spec:
  template:
    spec:
      hostIPC: true
      containers:
      - name: ssl
        image: pytorch/pytorch:1.8.0-cuda11.1-cudnn8-runtime
        workingDir: /storage/NO 6407-6-5
        command: ["/bin/bash", "-c"]
        args: [
          (
            pip install h5py &&
            python prepare_features.py --pretrained_weights "checkpoint.pth" --data_path "./hdf5/"
          )
          ] 
        stdin: true
        tty: true
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
      nodeSelector:
        kubernetes.io/hostname: barney # clancy: GeForce RTX A6000 48GB, edna: NVIDIA GeForce RTX 3090, barney: 12GB, apu: ?
  backoffLimit: 0
...